apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: ocs
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: ocs
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: ocs
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["ocs", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: OCS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: OCS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: OCS_HTTP_ADDR
              value: 0.0.0.0:9110

            - name: OCS_IDM_ADDRESS
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: OCS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.jwtSecretRef }}
                  name: jwt-secret
                  {{- else }}
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  {{- end }}
                  key: jwt-secret

            - name: OCS_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.machineAuthApiKeySecretRef }}
                  name: machine-auth-api-key
                  {{- else }}
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef }}
                  {{- end }}
                  key: machine-auth-api-key

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
          - name: http
            containerPort: 9110
