apiVersion: v1
kind: Service
metadata:
  name: ocs
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9110
      protocol: TCP
  selector:
    app: ocs
