{{- include "ocis.appNames" (dict "scope" . "appName" "appNameUserlog" "appNameSuffix" "") -}}
{{ include "ocis.hpa" . }}
{{- $_ := set . "autoscaling" (default (default (dict) .Values.autoscaling) .Values.services.userlog.autoscaling) -}}
