apiVersion: v1
kind: Service
metadata:
  name: accounts
  labels:
    app: accounts
spec:
  ports:
  - name: grpc
    port: 9180
    protocol: TCP
  - name: http
    port: 9181
    protocol: TCP
  selector:
    app: accounts
