apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-authbearer
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: storage-authbearer
  replicas: 1
  template:
    metadata:
      labels:
          app: storage-authbearer
    spec:
      containers:
        - name: storage-authbearer
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          command: ["ocis"]
          args: ["storage-auth-bearer", "server"]
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_AUTH_BEARER_GRPC_ADDR
              value: 0.0.0.0:9166
            - name: STORAGE_AUTH_BEARER_ENDPOINT
              value: "storage-authbearer:9166"

            - name: STORAGE_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          ports:
          - containerPort: 9166 # GRPC
