apiVersion: v1
kind: Service
metadata:
  name: storage-authbearer
  labels:
    app: storage-authbearer
spec:
  ports:
  - name: grpc
    port: 9166
    protocol: TCP
  selector:
    app: storage-authbearer
