apiVersion: v1
kind: Service
metadata:
  name: storage-authmachine
  labels:
    app: storage-authmachine
spec:
  ports:
  - name: grpc
    port: 9148
    protocol: TCP
  selector:
    app: storage-authmachine
