apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9140
      protocol: TCP
  selector:
    app: frontend
