apiVersion: v1
kind: Service
metadata:
  name: storage-authbasic
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 9146
    protocol: TCP
  selector:
    app: storage-authbasic
