apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-bearer
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: auth-bearer
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: auth-bearer
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: auth-bearer
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["auth-bearer", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: AUTH_BEARER_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: AUTH_BEARER_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: AUTH_BEARER_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: AUTH_BEARER_GRPC_ADDR
              value: 0.0.0.0:9148

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: AUTH_BEARER_OIDC_ISSUER
              value: https://{{ .Values.externalDomain }}

            - name: AUTH_BEARER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.jwtSecretRef }}
                  name: jwt-secret
                  {{- else }}
                  name: {{ .Values.secretRefs.jwtSecretRef}}
                  {{- end }}
                  key: jwt-secret

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9148
          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
