{{- if not .Values.features.externalUserManagement.enabled }}
{{- include "ocis.appNames" (dict "scope" . "appName" "appNameIdp" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.idp.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
  annotations:
    ignore-check.kube-linter.io/env-var-secret : "IDP_ENCRYPTION_SECRET_FILE is no secret, it's the file path to the secret"
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  replicas: 1
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          image: {{ template "ocis.image" $ }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["idp", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: IDP_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: IDP_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: IDP_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: IDP_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: IDP_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: IDP_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: IDP_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: IDP_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: IDP_HTTP_ADDR
              value: 0.0.0.0:9130
            - name: IDP_DEBUG_ADDR
              value: 0.0.0.0:9134

            - name: IDP_ISS
              value: "https://{{ .Values.externalDomain }}"

            - name: IDP_LDAP_URI
              value: ldaps://{{ .appNameIdm }}:9235

            - name: IDP_LDAP_TLS_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca.crt

            - name: IDP_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: idp-ldap-bind-password

            - name: IDP_LDAP_BIND_DN
              value: {{ .Values.features.externalUserManagement.ldap.bindDN | quote }}

            - name: IDP_SIGNING_PRIVATE_KEY_FILES
              value: /etc/ocis/idp/private-key.pem

            - name: IDP_ENCRYPTION_SECRET_FILE
              value: /etc/ocis/idp/encryption.key

            - name: IDP_INSECURE
              value: {{ .Values.features.externalUserManagement.ldap.insecure | quote }}

            - name: IDP_LDAP_LOGIN_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.userName | quote }}
            - name: IDP_LDAP_BASE_DN
              value: {{ .Values.features.externalUserManagement.ldap.user.baseDN | quote }}
            - name: IDP_LDAP_FILTER
              value: {{ .Values.features.externalUserManagement.ldap.user.filter | quote }}
            - name: IDP_LDAP_OBJECTCLASS
              value: {{ .Values.features.externalUserManagement.ldap.user.objectClass | quote }}
            - name: IDP_LDAP_UUID_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.id | quote }}
            - name: IDP_LDAP_EMAIL_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.mail | quote }}
            - name: IDP_LDAP_NAME_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.user.schema.userName | quote }}
            - name: IDP_LDAP_SCOPE
              value: {{ .Values.features.externalUserManagement.ldap.user.scope | quote }}

            - name: IDP_USER_ENABLED_ATTRIBUTE
              value: {{ .Values.features.externalUserManagement.ldap.disableUsers.userEnabledAttribute | quote }}

            - name: IDP_LDAP_UUID_ATTRIBUTE_TYPE
              value: {{ .Values.features.externalUserManagement.ldap.uuidAttributeType | quote }}

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: http
              containerPort: 9130
            - name: metrics-debug
              containerPort: 9134

          volumeMounts:
            - name: ocis-data-tmp
              mountPath: /var/lib/ocis # we mount that volume to apply fsGroup to that path, so that the idp can write the temporary idp/tmp/identifier-registration.yaml file
            - name: ocis-config-tmp
              mountPath: /etc/ocis # we mount that volume only to apply fsGroup to that path
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            - name: idp-secrets
              mountPath: /etc/ocis/idp
              readOnly: true

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: ocis-data-tmp
          emptyDir: {}
        - name: ocis-config-tmp
          emptyDir: {}
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
        - name: idp-secrets
          secret:
            secretName: {{ .Values.secretRefs.idpSecretRef }}
{{- end }}
