repositories:
  - name: rook-release
    url: https://charts.rook.io/release

releases:
  # rook ceph provides persistent volumes
  #- name: rook-ceph
  #  namespace: rook-ceph
  #  chart: rook-release/rook-ceph
  #- name: rook-ceph-cluster
  #  namespace: rook-ceph
  #  chart: rook-release/rook-ceph-cluster

  - name: ocis
    namespace: ocis-testing
    chart: ./ocis
    #values: