repositories:
  #- name: rook-release
  #  url: https://charts.rook.io/release
  - name: openebs
    url: https://openebs.github.io/charts

  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts

releases:
  - name: openebs-operator
    namespace: openebs
    chart: openebs/openebs
    #values:

  - name: prometheus
    namespace: prometheus
    chart: prometheus-community/kube-prometheus-stack
    values:
      - prometheus:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - prometheus.kube.w-kl.xyz
      - grafana:
          ingress:
            enabled: true
            ingressClassName: nginx
            hosts:
              - grafana.kube.w-kl.xyz


  #rook ceph provides persistent volumes
  #- name: rook-ceph-operator
  #  namespace: rook-ceph
  #  chart: rook-release/rook-ceph
  #  values:
  #    - hostpathRequiresPrivileged: true
  #- name: rook-ceph-cluster
  #  namespace: rook-ceph
  #  chart: rook-release/rook-ceph-cluster
  #  values:
  #    #- toolbox: true
  #    - cephClusterSpec:
  #        cephVersion:
  #          # see the "Cluster Settings" section below for more details on which image of ceph to run
  #          image: quay.io/ceph/ceph:v16.2.7
  #        dataDirHostPath: /var/lib/rook
  #        mon:
  #          count: 3
  #          allowMultiplePerNode: false
  #        storage:
  #          useAllNodes: true
  #          useAllDevices: true
  #          onlyApplyOSDPlacement: false

  - name: ocis
    namespace: ocis-testing
    chart: ./ocis
    values:
      - image:
          pullPolicy: Always

      - ingress:
          enabled: true
          ingressClassName: nginx

      - replicas: 3

      - autoscaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 10
          metrics:
          - type: Resource
            resource:
              name: cpu
              targetAverageUtilization: 60
          - type: Resource
            resource:
              name: memory
              targetAverageUtilization: 60

      - extraLabels:
          foo-bar: baz

      - resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 256Mi


      - thumbnails:
          persistence:
            enabled: true
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce

      - settings:
          persistence:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce

      - storageMetadata:
          persistence:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce

      - storageSharing:
          persistence:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce

      - storageUsers:
          persistence:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce
            size: 5Gi

      - store:
          persistence:
            storageClassName: openebs-hostpath
            accessModes:
              - ReadWriteOnce
