# when in local tunnel mode, ingressDomain is the proxy address.
ingressDomain: "https://neat-newt-12.loca.lt"

# base ocis image
image: owncloud/ocis:1.0.0-rc8-linux-amd64

#  required keys: metadata, labels, matchLabels, args
Services:
  Proxy:
    metadata:
      name: "ocis-proxy"
    labels:
      app: "ocis-proxy"
    matchLabels:
      app: "ocis-proxy"
    args: ["proxy"]
    ports:
      containerPort: 9200
    Env:
    - name: "OCIS_LOG_LEVEL"
      value: "debug"
    - name: "PROXY_REVA_GATEWAY_ADDR"
      value: "storages-service:9142"
    - name: "PROXY_ENABLE_BASIC_AUTH"
      value: "'true'" # see https://stackoverflow.com/a/44692213/2295410
    volumeMounts:
      - name: configs
        mountPath: /etc/ocis
    volumes:
      - name: configs
        configMap:
          name: proxy-config
  Ocs:
    metadata:
      name: "ocs"
    labels:
      app: "ocs"
    matchLabels:
      app: "ocs"
    args: ["ocs"]
  Storages:
    metadata:
      name: "storages"
    matchLabels:
      app: "storages"
    labels:
      app: "storages"
    containers:
      - name: accounts
        args: ["accounts"]
      - name: storage-frontend
        args: ["storage-frontend"]
      - name: storage-gateway
        args: ["storage-gateway"]
      - name: storage-userprovider
        args: ["storage-userprovider"]
      - name: storage-auth-basic
        args: ["storage-auth-basic"]
      - name: storage-auth-bearer
        args: ["storage-auth-bearer"]
        env:
          - name: STORAGE_OIDC_ISSUER
            value: "https://neat-newt-12.loca.lt" # TODO(refs) when in reverse tunnel needs to be read from a cli arg.
      - name: storage-home
        args: ["storage-home"]
        env:
          - name: "STORAGE_GATEWAY_ENDPOINT"
            value: "storages-service:9142"
      - name: storage-users
        args: ["storage-users"]
      - name: storage-metadata
        args: ["storage-metadata"]
      - name: storage-public-link
        args: ["storage-public-link"]
  Glauth:
    metadata:
      name: "glauth"
    matchLabels:
      app: "glauth"
    labels:
      app: "glauth"
    args: ["glauth"]
  Konnectd:
    metadata:
      name: "konnectd"
    matchLabels:
      app: "konnectd"
    labels:
      app: "konnectd"
    args: ["konnectd"]
    Env:
    - name: KONNECTD_ISS
      value: "https://neat-newt-12.loca.lt"
    - name: LDAP_URI
      value: "ldap://ldap-service:9125"
    - name: KONNECTD_IDENTIFIER_REGISTRATION_CONF
      value: "/etc/ocis/identifier-registration.yaml"
    - name: KONNECTD_INSECURE
      value: "'true'"
    - name: KONNECTD_TLS
      value: "'false'"
    - name: OCIS_LOG_LEVEL
      value: "debug"
    volumeMounts:
      - name: identifier-registration
        mountPath: /etc/ocis/
    volumes:
      - name: identifier-registration
        configMap:
          name: identifier-registration
  Settings:
    metadata:
      name: "settings"
    labels:
      app: "settings"
    matchLabels:
      app: "settings"
    args: ["settings"]
  Store:
    metadata:
      name: "store"
    labels:
      app: "store"
    matchLabels:
      app: "store"
    args: ["store"]
  Web:
    metadata:
      name: "web"
    labels:
      app: "web"
    matchLabels:
      app: "web"
    args: ["web"]
    Env:
    - name: "WEB_UI_CONFIG_SERVER"
      value: "https://neat-newt-12.loca.lt"
    - name: "WEB_OIDC_METADATA_URL"
      value: "https://neat-newt-12.loca.lt"
    - name: "WEB_OIDC_AUTHORITY"
      value: "https://neat-newt-12.loca.lt"
    ports:
      values:
      - name: "http"
        containerPort: 9100
        protocol: "TCP"