# when in local tunnel mode, ingressDomain is the proxy address.
ingressDomain: https://neat-newt-12.loca.lt

# base ocis image
image: owncloud/ocis:1.0.0-rc8-linux-amd64

Services:
  Proxy:
    metadata:
      name: "ocis-proxy"
    labels:
      app: "ocis-proxy"
    matchLabels:
      app: "ocis-proxy"
    args: ["proxy"]
    Ports:
      containerPort: 9200
    Env:
    - name: "OCIS_LOG_LEVEL"
      value: debug
    - name: "PROXY_REVA_GATEWAY_ADDR"
      value: "storages-service:9142"
    - name: "PROXY_ENABLE_BASIC_AUTH"
      value: "'true'"
    volumeMounts:
      - name: configs
        value: /etc/ocis
    volumes:
      - name: configs
        configMap:
          name: proxy-config
  Ocs:
    metadata:
      name: "ocs"
    labels:
      app: "ocs"
    matchLabels:
      app: "ocs"
    args: ["ocs"]
  Storages:
    metadata:
      name: "storages"
    matchLabels:
      app: "storages"
    labels:
      app: "storages"
    containers:
      - name: accounts
        args: ["accounts"]
      - name: storage-frontend
        args: ["storage-frontend"]
      - name: storage-gateway
        args: ["storage-gateway"]
      - name: storage-userprovider
        args: ["storage-userprovider"]
      - name: storage-auth-basic
        args: ["storage-auth-basic"]
      - name: storage-auth-bearer
        args: ["storage-auth-bearer"]
        env:
          - name: STORAGE_OIDC_ISSUER
            value: "https://neat-newt-12.loca.lt" # TODO(refs) when in reverse tunnel needs to be read from a cli arg.
      - name: storage-home
        args: ["storage-home"]
        env:
          - name: "STORAGE_GATEWAY_ENDPOINT"
            value: "storages-service:9142"
      - name: storage-users
        args: ["storage-users"]
      - name: storage-metadata
        args: ["storage-metadata"]
      - name: storage-public-link
        args: ["storage-public-link"]