# when in local tunnel mode, ingressDomain is the proxy address.
ingressDomain: https://neat-newt-12.loca.lt

# base ocis image
image: owncloud/ocis:1.0.0-rc8-linux-amd64

Services:
  Proxy:
    metadata:
      name: "ocis-proxy"
    labels:
      app: "ocis-proxy"
    matchLabels:
      app: "ocis-proxy"
    args: ["proxy"]
    containerPort: 9200
    Env:
      - name: "OCIS_LOG_LEVEL"
        value: "debug"
      - name: "PROXY_ENABLE_BASIC_AUTH"
        value: "true"
      - name: "PROXY_REVA_GATEWAY_ADDR"
        value: "storages-service:9142"
    volumeMounts:
      - name: configs
        value: /etc/ocis
    volumes:
      - name: configs
        configMap:
          name: proxy-config
  Ocs:
    metadata:
      name: "ocs"
    labels:
      app: "ocs"
    matchLabels:
      app: "ocs"
    args: ["ocs"]