---
apiVersion: v1
kind: Secret
metadata:
  name: jwtsecret
type: Opaque
data:
    # TODO: create random default value when no value is set in values.yaml https://github.com/owncloud/ocis-charts/issues/9
    password: "{{ b64enc $.Values.secrets.jwt }}"