---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secret
type: Opaque
data:
    # TODO: create random default value when no value is set in values.yaml https://github.com/owncloud/ocis-charts/issues/9
    OCIS_JWT_SECRET: "{{ b64enc $.Values.secrets.jwt }}"
    #ACCOUNTS_JWT_SECRET
    #ACCOUNTS_STORAGE_CS3_JWT_SECRET
    #GRAPH_JWT_SECRET
    #SETTINGS_JWT_SECRET
    #PROXY_JWT_SECRET
    #SETTINGS_JWT_SECRET
    #STORAGE_JWT_SECRET
