{{- if empty .Values.secretRefs.machineAuthApiKeySecretRef }}
apiVersion: v1
kind: Secret
metadata:
  name: machine-auth-api-key
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
  annotations:
    "helm.sh/resource-policy": "keep"
type: Opaque
data:
    {{- $secret := (lookup "v1" "Secret" .Release.Namespace "machine-auth-api-key") | default dict }} # TODO: use namespace template
    {{- $secretData := (get $secret "data") | default dict }}
    {{- $machineAuthApiKey := (get $secretData "machine-auth-api-key") | default (b64enc (randAlphaNum 32)) }}
    machine-auth-api-key: {{ $machineAuthApiKey }}
{{- end }}
