---
apiVersion: v1
kind: Secret
metadata:
  name: transfer-secret
type: Opaque
data:
    # TODO: create random default value when no value is set in values.yaml https://github.com/owncloud/ocis-charts/issues/9
    OCIS_TRANSFER_SECRET: "{{ b64enc $.Values.secrets.transfer }}"
    #STORAGE_TRANSFER_SECRET
