apiVersion: v1
kind: Service
metadata:
  name: graph
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: 9120
      protocol: TCP
  selector:
    app: graph
