releases:
  - name: ocis
    chart: ../../charts/ocis
    namespace: ocis
    values:
      - externalDomain: ocis.kube.owncloud.test
      - ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            nginx.ingress.kubernetes.io/proxy-body-size: 1024m
          tls:
            - secretName: ocis-dev-tls
              hosts:
                - ocis.kube.owncloud.test

      - logging:
          level: debug

      - insecure:
          oidcIdpInsecure: true
          ocisHttpApiInsecure: true

      - services:
          idm:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce

          nats:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce

          search:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce

          storagesystem:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce

          storageusers:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce

          store:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce

          thumbnails:
            persistence:
              enabled: true
              chownInitContainer: true
              accessModes:
                - ReadWriteOnce
