apiVersion: apps/v1
kind: Deployment
metadata:
  name: thumbnails
spec:
  selector:
    matchLabels:
        app: thumbnails
  replicas: 1
  template:
    metadata:
      labels:
          app: thumbnails
    spec:
      containers:
        - name: thumbnails
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["thumbnails", "server"]
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: THUMBNAILS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: THUMBNAILS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: THUMBNAILS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: THUMBNAILS_GRPC_ADDR
              value: 0.0.0.0:9185

            - name: THUMBNAILS_CS3SOURCE_INSECURE
              value: "true"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          ports:
          - containerPort: 9185 # GRPC

