apiVersion: monitoring.grafana.com/v1alpha1
kind: PodLogs
metadata:
  labels:
    instance: primary
  name: kubernetes-pods
spec:
  pipelineStages:
    - cri: {}
    - replace:
        expression: (([[:alnum:]]+).:)
        replace: "{{`{{ .Value | ToLower }}`}}"
  namespaceSelector:
    any: true
  selector:
    matchLabels: {}
