images:
  oCIS: owncloud/ocis:latest@sha256:72ce56d16bb5d5be4298277b2c9ac70a949f3664e4fbe7db4d14de314c3fe23f

logging:
  level: "debug"
  pretty: "true"
  color: "true"

external_domain: ocis.minikube.test

#TODO: define secrets in secrets...
secrets:
  jwt: foobar
  machineAuth: blabla
  transfer: lorem123

persistence:
  enabled: false
  storageClassName: standard
