images:
  oCIS: owncloud/ocis:latest@sha256:da5b43943329c60940f53cd56c66a7b8cb3aa6d5b43be531d960108b064a6928

logging:
  level: "debug"
  pretty: "true"
  color: "true"

externalDomain: ocis.kube.w-kl.xyz
tls:
  enabled: false

#TODO: define secrets in secrets...
secrets:
  jwt: foobar
  machineAuth: blabla
  transfer: lorem123

persistence:
  enabled: true
  storageClassName: rook-ceph-block
