images:
  oCIS: owncloud/ocis:latest

logging:
  level: "error"
  pretty: "true"
  color: "true"

external_domain: ocis.owncloud.test

#TODO: define secrets in secrets...
secrets:
  jwt: foobar
  machine_auth: blabla
  transfer_secret: lorem123
  metadata_jwt: 123abc

