apiVersion: v1
kind: Service
metadata:
  name: store
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
  - name: grpc
    port: 9460
    protocol: TCP
  selector:
    app: store
