apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-authbasic
spec:
  selector:
    matchLabels:
        app: storage-authbasic
  replicas: 1
  template:
    metadata:
      labels:
          app: storage-authbasic
    spec:
      containers:
        - name: storage-authbasic
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["storage-auth-basic", "server"]
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_AUTH_BASIC_GRPC_ADDR
              value: 0.0.0.0:9146
            - name: STORAGE_AUTH_BASIC_ENDPOINT
              value: "storage-authbasic:9146"

            - name: STORAGE_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          ports:
          - containerPort: 9146 # GRPC
