{{- include "ocis.appNames" (dict "scope" . "appName" "appNameThumbnails" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.thumbnails.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.serviceAccount" . | nindent 6 }}
      {{- include "ocis.affinity" .Values.services.thumbnails | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      {{- if and $.Values.services.thumbnails.persistence.enabled $.Values.services.thumbnails.persistence.chownInitContainer }}
      initContainers:
        - name: init-chown-data
          {{- include "ocis.initContainerImage" $ | nindent 10 }}
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/var/lib/ocis"]
          volumeMounts:
          - name: thumbnails-data
            mountPath: /var/lib/ocis
      {{ end }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["thumbnails", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: THUMBNAILS_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: THUMBNAILS_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: THUMBNAILS_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: THUMBNAILS_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: THUMBNAILS_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: THUMBNAILS_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: THUMBNAILS_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: THUMBNAILS_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: THUMBNAILS_GRPC_ADDR
              value: 0.0.0.0:9185
            - name: THUMBNAILS_HTTP_ADDR
              value: 0.0.0.0:9186
            - name: THUMBNAILS_DEBUG_ADDR
              value: 0.0.0.0:9189

            - name: THUMBNAILS_DATA_ENDPOINT
              value: http://{{ .appName }}:9186/thumbnails/data

            - name: THUMBNAILS_WEBDAVSOURCE_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            - name: THUMBNAILS_CS3SOURCE_INSECURE
              value: {{ .Values.insecure.ocisHttpApiInsecure | quote }}

            - name: OCIS_REVA_GATEWAY
              value: com.owncloud.api.gateway

            - name: THUMBNAILS_TRANSFER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.thumbnailsSecretRef }}
                  key: thumbnails-transfer-secret

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9185
            - name: http
              containerPort: 9186
            - name: metrics-debug
              containerPort: 9189

          volumeMounts:
            - name: thumbnails-data
              mountPath: /var/lib/ocis

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: thumbnails-data
          {{ if .Values.services.thumbnails.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .appName }}-data
          {{ else }}
          emptyDir: {}
          {{ end }}
