apiVersion: v1
kind: Service
metadata:
  name: storage-authbearer
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: 9166
      protocol: TCP
  selector:
    app: storage-authbearer
