apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-sharing
spec:
  selector:
    matchLabels:
        app: storage-sharing
  replicas: 1
  template:
    metadata:
      labels:
          app: storage-sharing
    spec:
      containers:
        - name: store
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["storage-sharing", "server"]
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_SHARING_GRPC_ADDR
              value: 0.0.0.0:9150
            - name: STORAGE_SHARING_ENDPOINT
              value: 'storage-users:9150'

            - name: STORAGE_USERS_HTTP_ADDR
              value: 0.0.0.0:9158
            - name: STORAGE_USERS_DATA_SERVER_URL
              value: "http://storage-users:9158/data"

            - name: STORAGE_SHARING_USER_DRIVER
              value: "json"
            - name: STORAGE_SHARING_PUBLIC_DRIVER
              value: "json"

            - name: STORAGE_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"
            - name: REVA_GATEWAY
              value: "storage-gateway:9142"
          ports:
          - containerPort: 9150 # GRPC
#          volumeMounts:
#          - name: storage-sharing-data
#            mountPath: /var/lib/ocis
#      volumes:
#        - name: storage-sharing-data
#          persistentVolumeClaim:
#            claimName: storage-sharing-data
