{{- include "ocis.appNames" (dict "scope" . "appName" "appNameProxy" "appNameSuffix" "") -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .appName }}-config
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
data:
  proxy.yaml: |
    ---
    policy_selector:
      static:
        policy: ocis
    {{- with $.Values.features.quotas.roles }}
    role_quotas:
      {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- if $.Values.features.externalUserManagement.oidc.roleAssignment.enabled }}
    role_assignment:
      driver: oidc
      {{- if or $.Values.features.externalUserManagement.oidc.roleAssignment.claim $.Values.features.externalUserManagement.oidc.roleAssignment.mapping }}
      oidc_role_mapper:
        {{- with $.Values.features.externalUserManagement.oidc.roleAssignment.claim }}
        role_claim: {{ . }}
        {{- end }}
        {{- with $.Values.features.externalUserManagement.oidc.roleAssignment.mapping }}
        role_mapping:
          {{- toYaml . | nindent 10 }}
        {{- end }}
      {{- end }}
    {{- end }}
    policies:
    - name: ocis
      routes:
      - endpoint: /
        service: com.owncloud.web.web
        unprotected: true
      - endpoint: /.well-known/openid-configuration
        service: com.owncloud.web.idp
        unprotected: true
      - endpoint: /branding/logo
        service: com.owncloud.web.web
      - endpoint: /konnect/
        service: com.owncloud.web.idp
        unprotected: true
      - endpoint: /signin/
        service: com.owncloud.web.idp
        unprotected: true
      - endpoint: /archiver
        service: com.owncloud.web.frontend
      - endpoint: /ocs/v2.php/apps/notifications/api/v1/notifications
        service: com.owncloud.userlog.userlog
      - type: regex
        endpoint: /ocs/v[12].php/cloud/user/signing-key
        service: com.owncloud.web.ocs
      - type: regex
        endpoint: /ocs/v[12].php/config
        service: com.owncloud.web.frontend
        unprotected: true
      - endpoint: /ocs/
        service: com.owncloud.web.frontend
      - type: query
        endpoint: /remote.php/?preview=1
        service: com.owncloud.web.webdav
      - method: REPORT
        endpoint: /remote.php/dav/
        service: com.owncloud.web.webdav
      - method: REPORT
        endpoint: /remote.php/webdav
        service: com.owncloud.web.webdav
      - method: REPORT
        endpoint: /dav/spaces
        service: com.owncloud.web.webdav
      - type: query
        endpoint: /dav/?preview=1
        service: com.owncloud.web.webdav
      - type: query
        endpoint: /webdav/?preview=1
        service: com.owncloud.web.webdav
      - endpoint: /remote.php/
        service: com.owncloud.web.ocdav
      - endpoint: /dav/
        service: com.owncloud.web.ocdav
      - endpoint: /webdav/
        service: com.owncloud.web.ocdav
      - endpoint: /status
        service: com.owncloud.web.ocdav
        unprotected: true
      - endpoint: /status.php
        service: com.owncloud.web.ocdav
        unprotected: true
      - endpoint: /index.php/
        service: com.owncloud.web.ocdav
      - endpoint: /apps/
        service: com.owncloud.web.ocdav
      - endpoint: /data
        service: com.owncloud.web.frontend
        unprotected: true
      - endpoint: /app/list
        service: com.owncloud.web.frontend
        unprotected: true
      - endpoint: /app/
        service: com.owncloud.web.frontend
      - endpoint: /graph/
        service: com.owncloud.graph.graph
      - endpoint: /api/v0/settings
        service: com.owncloud.web.settings
