apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: proxy
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: proxy
        {{- include "ocis.labels" . | nindent 8 }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/proxy/config.yaml") . | sha256sum }}
    spec:
      containers:
        - name: proxy
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["proxy", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: PROXY_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: PROXY_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: PROXY_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: PROXY_HTTP_ADDR
              value: 0.0.0.0:9200

            - name: PROXY_ENABLE_BASIC_AUTH
              value: "true" #TODO: configurable
            - name: PROXY_OIDC_ISSUER
              value: "https://{{ .Values.externalDomain }}"
            - name: PROXY_TLS
              value: "false"

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: PROXY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.jwtSecretRef }}
                  name: jwt-secret
                  {{- else }}
                  name: {{ .Values.secretRefs.jwtSecretRef}}
                  {{- end }}
                  key: jwt-secret

            - name: PROXY_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.machineAuthApiKeySecretRef }}
                  name: machine-auth-api-key
                  {{- else }}
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef}}
                  {{- end }}
                  key: machine-auth-api-key

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9200
          volumeMounts:
            - name: configs
              mountPath: /etc/ocis
      volumes:
        - name: configs
          configMap:
            name: proxy-config
