apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: users
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: users
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: users
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["users", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: USERS_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: USERS_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: USERS_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: USERS_GRPC_ADDR
              value: 0.0.0.0:9144

            - name: USERS_LDAP_URI
              value: ldaps://idm:9235
            - name: USERS_LDAP_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca.crt
            - name: USERS_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.ldapSecretRef }}
                  key: reva-ldap-bind-password
            - name: USERS_IDP_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: USERS_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: grpc
              containerPort: 9144
          volumeMounts:
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: ldap-ca
          secret:
            secretName: {{ .Values.secretRefs.ldapCaRef }}
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
