apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
  - name: nats
    port: 9233
    protocol: TCP
  selector:
    app: nats
