apiVersion: apps/v1
kind: Deployment
metadata:
  name: search
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: search
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: search
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      initContainers:
        - name: init-chown-data
          image: busybox
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
          command: ["chown", "-R", "1000:1000", "/var/lib/ocis"]
          volumeMounts:
          - name: search-data
            mountPath: /var/lib/ocis
      containers:
        - name: search
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["search", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: SEARCH_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: SEARCH_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: SEARCH_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: SEARCH_GRPC_ADDR
              value: 0.0.0.0:9220

            - name: REVA_GATEWAY
              value: gateway:9142
            - name: SEARCH_EVENTS_ENDPOINT
              value: nats:9233

            - name: SEARCH_MACHINE_AUTH_API_KEY
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.machineAuthApiKeySecretRef }}
                  name: machine-auth-api-key
                  {{- else }}
                  name: {{ .Values.secretRefs.machineAuthApiKeySecretRef}}
                  {{- end }}
                  key: machine-auth-api-key

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
          - name: grpc
            containerPort: 9220
          volumeMounts:
            - name: search-data
              mountPath: /var/lib/ocis
      volumes:
      {{- if .Values.search.persistence.enabled }}
        - name: search-data
          persistentVolumeClaim:
            claimName: search-data
      {{ else }}
        - name: search-data
          emptyDir: {}
      {{ end }}
