apiVersion: v1
kind: Service
metadata:
  name: search
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    app: search
  ports:
    - name: grpc
      port: 9220
      protocol: TCP
    - name: metrics-debug
      port: 9224
      protocol: TCP
