apiVersion: v1
kind: ConfigMap
metadata:
  name: local-config
data:
  local.json: |
    {
        "services": {
            "CoAuthoring": {
                "autoAssembly": {
                    "enable": true,
                    "interval": "5m"
                }
            }
        }
    }
