apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocis-service-registry
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: ocis-service-registry
subjects:
- kind: ServiceAccount
  name: default
  namespace: {{ $.Release.Namespace }}
