apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-frontend
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: storage-frontend
  replicas: 1
  template:
    metadata:
      labels:
          app: storage-frontend
    spec:
      containers:
        - name: storage-frontend
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          command: ["ocis"]
          args: ["storage-frontend", "server"]
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: STORAGE_FRONTEND_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: STORAGE_FRONTEND_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: STORAGE_FRONTEND_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_FRONTEND_HTTP_ADDR
              value: 0.0.0.0:9140
            - name: STORAGE_FRONTEND_PUBLIC_URL
              value: "https://{{ $.Values.externalDomain }}"

            - name: STORAGE_FRONTEND_APPPROVIDER_INSECURE
              value: "true"
            - name: STORAGE_FRONTEND_ARCHIVER_INSECURE
              value: "true"
            - name: STORAGE_FRONTEND_OCDAV_INSECURE
              value: "true"

            - name: STORAGE_SHARING_ENDPOINT
              value: "storage-sharing:9150"

            - name: STORAGE_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"
            - name: STORAGE_TRANSFER_SECRET
              value: "{{ $.Values.secrets.transfer }}"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          ports:
          - containerPort: 9140 # HTTP
