apiVersion: v1
kind: Service
metadata:
  name: storage-frontend
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 9140
    protocol: TCP
  selector:
    app: storage-frontend
