apiVersion: v1
kind: Service
metadata:
  name: storage-frontend
  labels:
    app: storage-frontend
spec:
  ports:
  - name: http
    port: 9140
    protocol: TCP
  selector:
    app: storage-frontend
