{{- range .Values.services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .metadata.name }}
spec:
  selector:
    matchLabels:
      {{- range $key, $val := .matchLabels}}
        {{ $key }}: {{ $val }}
      {{- end}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- range $key, $val := .labels}}
          {{ $key }}: {{ $val }}
          {{- end}}
    spec:
    {{- if .containers }}
      containers:
      {{- range .containers }}
        - name: {{ .name }}
          image: {{ $.Values.image }}
          command: ["ocis"]
          args: {{ .args }}
        {{- if .env }}
          env:
        {{- range .env }}
          - name: {{ .name }}
            value: {{ .value }}
        {{- end}}
        {{- end }}
      {{- end}}
    {{ else }}
      containers:
        - name: {{ .metadata.name }}
          image: {{ $.Values.image }}
          command: ["ocis"]
          args: {{ .args }}

          {{- if .env }}
          env:
          {{- range .env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end  }}
          {{- end }}

          {{- if .ports }}
          ports:
          {{- if .ports.containerPort }}
          - containerPort: {{ .ports.containerPort }}
          {{- end }}
            {{- if .ports.values }}
              {{- range .ports.values }}
          - name: {{ .name }}
            containerPort: {{ .containerPort }}
            protocol: {{ .protocol }}
              {{- end }}
            {{- end }}
          {{- end }}

          {{- if .volumeMounts }}
          volumeMounts:
          {{- range .volumeMounts}}
          - name: {{ .name }}
            mountPath: {{ .mountPath }}
          {{- end}}
          {{- end }}

      {{- if .volumes }}
      volumes:
      {{- range .volumes}}
        - name: {{ .name }}
        {{- if .configMap }}
          configMap:
            name: {{ .configMap.name }}
        {{- end }}
      {{- end}}
      {{- end }}
      {{- end }}
{{- /*
  because we're iterating over a bunch of objects and generating yaml, this needs to be valid. As long
  as we keep concatenating "---" at the end of each file, we're good. The convention is to use one tem-
  plate per deployment, but for our case that would bloat quite a bit. For the sake of readibility,
  we should look into take that approach. Check https://github.com/helm/charts/tree/master/stable/prometheus
  for reference.
*/}}
---
{{- end }}