---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocs
spec:
  selector:
    matchLabels:
        app: ocs
  replicas: 1
  template:
    metadata:
      labels:
          app: ocs
    spec:
      containers:
        - name: ocs
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["ocs", "server"]
          env:
            - name: OCS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: OCS_HTTP_ADDR
              value: 0.0.0.0:9110

            - name: OCS_ACCOUNT_BACKEND_TYPE
              value: "accounts"
            - name: OCS_IDM_ADDRESS
              value: "https://{{ $.Values.external_domain }}"

            - name: OCS_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"
            - name: PROXY_MACHINE_AUTH_API_KEY
              value: "{{ $.Values.secrets.machine_auth }}"
            
            - name: REVA_GATEWAY
              value: storage-gateway:9142
          ports:
          - containerPort: 9110 # HTTP
---