---
apiVersion: v1
kind: Service
metadata:
  name: settings
  labels:
    app: settings
spec:
  ports:
  - name: grpc
    port: 9191
    protocol: TCP
  - name: http
    port: 9190
    protocol: TCP
  selector:
    app: settings

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: settings
spec:
  selector:
    matchLabels:
        app: settings
  replicas: 1
  template:
    metadata:
      labels:
          app: settings
    spec:
      containers:
        - name: settings
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["settings", "server"]
          env:
            - name: SETTINGS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: SETTINGS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: SETTINGS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: SETTINGS_HTTP_ADDR
              value: 0.0.0.0:9190
            - name: SETTINGS_GRPC_ADDR
              value: 0.0.0.0:9191

            - name: SETTINGS_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"
          ports:
          - containerPort: 9190 # HTTP
          - containerPort: 9191 # GRPC
#          volumeMounts:
#          - name: settings-data
#            mountPath: /var/lib/ocis
#      volumes:
#        - name: settings-data
#          persistentVolumeClaim:
#            claimName: settings-data
#---
#apiVersion: v1
#kind: PersistentVolume
#metadata:
#  name: settings-data
#  labels:
#    name: settings-data
#spec:
#  accessModes:
#  - ReadOnlyMany
#  capacity:
#    storage: 5Gi
#  storageClassName: "{{ $.Values.persistence.storageClassName }}"
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: settings-data
#spec:
#  accessModes:
#  - ReadOnlyMany
#  resources:
#    requests:
#      storage: 5Gi
#  storageClassName: "{{ $.Values.persistence.storageClassName }}"
#  selector:
#    matchLabels:
#      name: settings-data
#---