---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-groupprovider
spec:
  selector:
    matchLabels:
        app: storage-groupprovider
  replicas: 1
  template:
    metadata:
      labels:
          app: storage-groupprovider
    spec:
      containers:
        - name: storage-groupprovider
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["storage-groupprovider", "server"]
          env:
            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_GROUPPROVIDER_ADDR
              value: 0.0.0.0:9160
            - name: STORAGE_GROUPPROVIDER_ENDPOINT
              value: "storage-groupprovider:9160"

            - name: STORAGE_GROUPPROVIDER_DRIVER
              value: "ldap"
            - name: STORAGE_LDAP_HOSTNAME
              value: "glauth"
            - name: STORAGE_LDAP_PORT
              value: "9126"
            - name: STORAGE_LDAP_INSECURE
              value: "'true'"

            - name: STORAGE_LDAP_IDP
              value: "https://{{ $.Values.external_domain }}"

            - name: STORAGE_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"

            - name: REVA_GATEWAY
              value: storage-gateway:9142
          ports:
          - containerPort: 9160 # GRPC
---