---
apiVersion: v1
kind: Service
metadata:
  name: storage-gateway
  labels:
    app: storage-gateway
spec:
  ports:
  - name: grpc
    port: 9142
    protocol: TCP
  selector:
    app: storage-gateway


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-gateway
spec:
  selector:
    matchLabels:
        app: storage-gateway
  replicas: 2 # TODO: minimum 2, else REVA_GATEWAY won't resolve for itself
  template:
    metadata:
      labels:
          app: storage-gateway
    spec:
      containers:
        - name: storage-gateway
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["storage-gateway", "server"]
          env:
            - name: OCIS_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: OCIS_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: OCIS_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: STORAGE_GATEWAY_GRPC_ADDR
              value: 0.0.0.0:9142
            - name: REVA_GATEWAY
              value: storage-gateway:9142

            - name: STORAGE_FRONTEND_PUBLIC_URL
              value: "https://{{ $.Values.external_domain }}"

            - name: STORAGE_USERS_ENDPOINT
              value: "storage-users:9157"
            
            - name: STORAGE_PUBLIC_LINK_ENDPOINT
              value: "storage-publiclink:9178"
            
            - name: STORAGE_AUTH_BASIC_ENDPOINT
              value: "storage-authbasic:9146"
            - name: STORAGE_AUTH_BEARER_ENDPOINT
              value: "storage-authbearer:9166"
            - name: STORAGE_AUTH_MACHINE_ENDPOINT
              value: "storage-authmachine:9148"

            - name: STORAGE_SHARES_ENDPOINT
              value: "storage-shares:9154"
            - name: STORAGE_SHARING_ENDPOINT
              value: "storage-sharing:9150"
            
            - name: STORAGE_GROUPPROVIDER_ENDPOINT
              value: "storage-groupprovider:9160"
            - name: STORAGE_USERPROVIDER_ENDPOINT
              value: "storage-userprovider:9144"

            - name: STORAGE_JWT_SECRET
              value: "{{ $.Values.secrets.jwt }}"
            - name: STORAGE_TRANSFER_SECRET
              value: "{{ $.Values.secrets.transfer }}"
          ports:
            - containerPort: 9142 # GRPC
---