---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdav
spec:
  selector:
    matchLabels:
        app: webdav
  replicas: 1
  template:
    metadata:
      labels:
          app: webdav
    spec:
      containers:
        - name: webdav
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["webdav", "server"]
          env:
            - name: WEBDAV_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: WEBDAV_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: WEBDAV_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: WEBDAV_HTTP_ADDR
              value: 0.0.0.0:9115
            
            - name: OCIS_PUBLIC_URL
              value: "https://{{ $.Values.external_domain }}"
            - name: REVA_GATEWAY
              value: "storage-gateway:9142"
          ports:
          - containerPort: 9115 # HTTP
---