apiVersion: apps/v1
kind: Deployment
metadata:
  name: graph-explorer
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: graph-explorer
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: graph-explorer
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: graph-explorer
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["graph-explorer", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GRAPH_EXPLORER_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: GRAPH_EXPLORER_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: GRAPH_EXPLORER_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: GRAPH_EXPLORER_HTTP_ADDR
              value: 0.0.0.0:9135

            - name: GRAPH_EXPLORER_ISSUER
              value: https://{{ .Values.externalDomain }}
            - name: GRAPH_EXPLORER_GRAPH_URL_BASE
              value: https://{{ .Values.externalDomain }}

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: 9135
