apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocis-service-registry
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
rules:
- apiGroups:
  - "" # "" indicates the core API group
  resources:
  - pods
  verbs:
  - list
  - patch
  - watch
