apiVersion: apps/v1
kind: Deployment
metadata:
  name: glauth
spec:
  selector:
    matchLabels:
        app: glauth
  replicas: 1
  template:
    metadata:
      labels:
          app: glauth
    spec:
      containers:
        - name: glauth
          image: "{{ $.Values.images.oCIS }}"
          command: ["ocis"]
          args: ["glauth", "server"]
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GLAUTH_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: GLAUTH_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: GLAUTH_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: GLAUTH_LDAP_ADDR
              value: 0.0.0.0:9125
            - name: GLAUTH_LDAPS_ADDR
              value: 0.0.0.0:9126

            - name: GLAUTH_BACKEND_INSECURE
              value: "true"
          ports:
          - containerPort: 9125 # LDAP
          - containerPort: 9126 # LDAPS
