apiVersion: v1
kind: Service
metadata:
  name: auth-machine
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: grpc
      port: 9166
      protocol: TCP
  selector:
    app: auth-machine
