apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-basic
  namespace: {{ template "ocis.namespace" $ }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: auth-basic
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
        app: auth-basic
        {{- include "ocis.labels" . | nindent 8 }}
    spec:
      containers:
        - name: auth-basic
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["auth-basic", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: AUTH_BASIC_LOG_COLOR
              value: "{{ .Values.logging.color }}"
            - name: AUTH_BASIC_LOG_LEVEL
              value: "{{ .Values.logging.level }}"
            - name: AUTH_BASIC_LOG_PRETTY
              value: "{{ .Values.logging.pretty }}"

            - name: AUTH_BASIC_GRPC_ADDR
              value: 0.0.0.0:9146

            - name: REVA_GATEWAY
              value: gateway:9142

            - name: AUTH_BASIC_LDAP_URI
              value: ldaps://idm:9235
            - name: AUTH_BASIC_LDAP_CACERT
              value: /etc/ocis/ldap-ca/ldap-ca-cert

            - name: AUTH_BASIC_LDAP_BIND_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ldap-bind-secrets
                  key: reva-ldap-bind-password

            - name: AUTH_BASIC_IDP_URL
              value: https://{{ .Values.externalDomain }}

            - name: AUTH_BASIC_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  {{- if empty .Values.secretRefs.jwtSecretRef }}
                  name: jwt-secret
                  {{- else }}
                  name: {{ .Values.secretRefs.jwtSecretRef}}
                  {{- end }}
                  key: jwt-secret

          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
          - name: grpc
            containerPort: 9146
          volumeMounts:
            - name: ldap-ca
              mountPath: /etc/ocis/ldap-ca
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
      volumes:
        - name: ldap-ca
          secret:
            secretName: ldap-ca
        - name: tmp-volume
          emptyDir:
            medium: Memory
            sizeLimit: 6Mi
