apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "proxy"
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ $.Values.externalDomain }}"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: "proxy"
                port:
                  number: 9200
