{{- range .Values.Services }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .metadata.name }}
spec:
  selector:
    matchLabels:
      {{- range $key, $val := .matchLabels}}
        {{ $key }}: {{ $val }}
      {{- end}}
  replicas: 1
  template:
    metadata:
      labels:
        {{- range $key, $val := .labels}}
          {{ $key }}: {{ $val }}
          {{- end}}
    spec:
    {{- if .containers }}
      containers:
      {{- range .containers }}
        - name: {{ .name }}
          image: {{ $.Values.image }}
          command: ["ocis"]
          args: {{ .args }}
        {{- if .env }}
          env:
        {{- range .env }}
          - name: {{ .name }}
            value: {{ .value }}
        {{- end}}
        {{ end }}
      {{- end}}
    {{ else }}
      containers:
        - name: {{ .metadata.name }}
          image: {{ $.Values.image }}
          command: ["ocis"]
          args: {{ .args }}

          {{- if .Env }}
          env:
          {{- range .Env }}
            - name: {{ .name }}
              value: {{ .value }}
          {{- end  }}
          {{ end }}

          {{- if .Ports }}
          ports:
          {{- if .Ports.containerPort }}
          - containerPort: {{ .Ports.containerPort }}
          {{ end }}
          {{ end }}

          {{- if .volumeMounts }}
          volumeMounts:
            - name: configs
              mountPath: /etc/ocis/
          {{ end }}

      {{- if .volumes }}
      volumes:
        - name: configs
          configMap:
            name: proxy-config
      {{ end }}
      {{ end }}
---
{{- end }}