apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 9100
    protocol: TCP
  selector:
    app: web
