apiVersion: apps/v1
kind: Deployment
metadata:
  name: glauth
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
        app: glauth
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- if .Values.deploymentStrategy }}
  strategy: {{ toYaml .Values.deploymentStrategy | nindent 4 }}
  {{ end }}
  template:
    metadata:
      labels:
          app: glauth
    spec:
      containers:
        - name: glauth
          {{- if .Values.image.sha }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}@sha256:{{ .Values.image.sha }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["ocis"]
          args: ["glauth", "server"]
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GLAUTH_LOG_COLOR
              value: "{{ $.Values.logging.color }}"
            - name: GLAUTH_LOG_LEVEL
              value: "{{ $.Values.logging.level }}"
            - name: GLAUTH_LOG_PRETTY
              value: "{{ $.Values.logging.pretty }}"

            - name: GLAUTH_LDAP_ADDR
              value: 0.0.0.0:9125
            - name: GLAUTH_LDAPS_ADDR
              value: 0.0.0.0:9126

            - name: GLAUTH_BACKEND_INSECURE
              value: "true"
          resources: {{ toYaml .Values.resources | nindent 12 }}
          ports:
          - name: ldap
            containerPort: 9125
          - name: ldaps
            containerPort: 9126
