{{- include "ocis.appNames" (dict "scope" . "appName" "appNameGateway" "appNameSuffix" "") -}}
{{- $_ := set . "resources" (default (default (dict) .Values.resources) .Values.services.gateway.resources) -}}
apiVersion: apps/v1
kind: Deployment
{{ include "ocis.metadata" . }}
spec:
  {{- include "ocis.selector" . | nindent 2 }}
  {{- if and (not .Values.autoscaling.enabled) (.Values.replicas) }}
  replicas: {{ .Values.replicas }}
  {{- end }}
  {{- include "ocis.deploymentStrategy" . | nindent 2 }}
  template:
    {{- include "ocis.templateMetadata" (dict "scope" $ "configCheck" false) | nindent 4 }}
    spec:
      {{- include "ocis.serviceAccount" . | nindent 6 }}
      {{- include "ocis.affinity" .Values.services.gateway | nindent 6 }}
      {{- include "ocis.securityContextAndtopologySpreadConstraints" . | nindent 6 }}
      containers:
        - name: {{ .appName }}
          {{- include "ocis.image" $ | nindent 10 }}
          command: ["ocis"]
          args: ["gateway", "server"]
          {{- include "ocis.containerSecurityContext" . | nindent 10 }}
          env:
            - name: MICRO_REGISTRY
              value: kubernetes

            - name: GATEWAY_LOG_COLOR
              value: {{ .Values.logging.color | quote }}
            - name: GATEWAY_LOG_LEVEL
              value: {{ .Values.logging.level | quote }}
            - name: GATEWAY_LOG_PRETTY
              value: {{ .Values.logging.pretty | quote }}

            - name: GATEWAY_TRACING_ENABLED
              value: "{{ .Values.tracing.enabled }}"
            - name: GATEWAY_TRACING_TYPE
              value: {{ .Values.tracing.type | quote }}
            - name: GATEWAY_TRACING_ENDPOINT
              value: {{ .Values.tracing.endpoint | quote }}
            - name: GATEWAY_TRACING_COLLECTOR
              value: {{ .Values.tracing.collector | quote }}

            - name: GATEWAY_DEBUG_PPROF
              value: {{ .Values.debug.profiling | quote }}

            - name: GATEWAY_GRPC_ADDR
              value: 0.0.0.0:9142
            - name: GATEWAY_DEBUG_ADDR
              value: 0.0.0.0:9143

            - name: OCIS_REVA_GATEWAY
              # we also could have gateway:9142 here, but some
              # Kubernetes distributions as minikube do not support
              # resolving a container's hostname in the container.
              value: com.owncloud.api.gateway

            - name: GATEWAY_FRONTEND_PUBLIC_URL
              value: "https://{{ .Values.externalDomain }}"

            - name: GATEWAY_USERS_ENDPOINT
              value: com.owncloud.api.users
            - name: GATEWAY_GROUPS_ENDPOINT
              value: com.owncloud.api.groups

            - name: GATEWAY_AUTH_BASIC_ENDPOINT
              value: com.owncloud.api.auth-basic
            - name: GATEWAY_AUTH_MACHINE_ENDPOINT
              value: com.owncloud.api.auth-machine

            - name: GATEWAY_PERMISSIONS_ENDPOINT
              value: com.owncloud.api.settings

            - name: GATEWAY_SHARING_ENDPOINT
              value: com.owncloud.api.sharing
            - name: GATEWAY_STORAGE_PUBLIC_LINK_ENDPOINT
              value: com.owncloud.api.storage-publiclink
            - name: GATEWAY_STORAGE_USERS_ENDPOINT
              value: com.owncloud.api.storage-users
            - name: GATEWAY_STORAGE_SHARES_ENDPOINT
              value: com.owncloud.api.storage-shares

            - name: GATEWAY_APP_REGISTRY_ENDPOINT
              value: com.owncloud.api.app-registry

            # cache
            # the stat cache is disabled for now for performance reasons, see https://github.com/owncloud/ocis-charts/issues/214
            - name: GATEWAY_STAT_CACHE_STORE
              value: noop
            # provider cache in kubernetes defaults to noop because we might have regularily changing ip addresses
            - name: GATEWAY_PROVIDER_CACHE_STORE
              value: noop
            # create home cache defaults to memory so we don't put too much load on our shared cache
            - name: GATEWAY_CREATE_HOME_CACHE_STORE
              value: memory

            - name: GATEWAY_STORAGE_USERS_MOUNT_ID
              valueFrom:
                configMapKeyRef:
                  name: {{ .Values.configRefs.storageusersConfigRef }}
                  key: storage-uuid

            - name: GATEWAY_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.jwtSecretRef }}
                  key: jwt-secret

            - name: OCIS_TRANSFER_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secretRefs.transferSecretSecretRef }}
                  key: transfer-secret

          {{- include "ocis.livenessProbe" . | nindent 10 }}

          resources: {{ toYaml .resources | nindent 12 }}

          ports:
            - name: grpc
              containerPort: 9142
            - name: metrics-debug
              containerPort: 9143

          volumeMounts:
            - name: tmp-volume
              mountPath: /tmp

      {{- include "ocis.imagePullSecrets" $ | nindent 6 }}
      volumes:
        - name: tmp-volume
          emptyDir: {}
