apiVersion: v1
kind: Service
metadata:
  name: storage-groupprovider
  labels:
    app: storage-groupprovider
spec:
  ports:
  - name: grpc
    port: 9160
    protocol: TCP
  selector:
    app: storage-groupprovider
