apiVersion: v1
kind: Service
metadata:
  name: idm
  namespace: {{ template "ocis.namespace" . }}
  labels:
    {{- include "ocis.labels" . | nindent 4 }}
spec:
  ports:
    - name: ldaps
      port: 9235
      protocol: TCP
  selector:
    app: idm
